apiVersion: v1
stringData:
  DB_NAME: "postgres"
  DB_HOST: "192.168.0.3"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  BROKER_HOST: "pulsar-standalone-service:6650"
kind: Secret
metadata:
  name: secrets-propiedadesalpes